services:
  cadp-integration:
    depends_on:
      - kmip-client
    build:
      context: ./cadp-dotnet-client
    ports:
      - "${WEB_PORT:-8080}:8080"
    env_file: .env
    networks:
      - cadp-net
    volumes:
      - ./logs:/app/logs
      - ./test-vectors:/app/test-vectors
      - ./Cert:/certs:ro

  kmip-client:
    build:
      context: ./kmip-client
    env_file: .env
    networks:
      - cadp-net
    volumes:
      - ./Cert:/certs:ro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - cadp-integration
    networks:
      - cadp-net

networks:
  cadp-net:
    driver: bridge

