services:
  cadp-integration:
    build:
      context: ./cadp-dotnet-client
    ports:
      - "${WEB_PORT:-8080}:8080"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./test-vectors:/app/test-vectors
      - "/home/arham-jamal/Desktop/Certificate (1).pem:/certs/Certificate (1).pem:ro"
      - "/home/arham-jamal/Desktop/client.crt:/certs/client.crt:ro"
      - "/home/arham-jamal/Desktop/client.key:/certs/client.key:ro"

  kmip-client:
    build:
      context: ./kmip-client
    env_file: .env
    volumes:
      - "/home/arham-jamal/Desktop/Certificate (1).pem:/certs/Certificate (1).pem:ro"
      - "/home/arham-jamal/Desktop/client.crt:/certs/client.crt:ro"
      - "/home/arham-jamal/Desktop/client.key:/certs/client.key:ro"

